Reuse node_modules from build step instead of reinstalling
It should be ok to assume that 'npm install' has just been run when the
docker build is initiated.

We need node_modules at runtime, without it we are getting this error:

Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'